f = [

    "enlarged prostate (proximic agent)",
    "zipline prostate disorders",
    "crossix > crossix ga > diagnosis > atrial fibrillation > 1",
    "epsilon: healthcare > conditions > heart conditions > irregular heart rhythm",
    "crossix > crossix ga > diagnosis > congestive heart failure > 2",
    "crossix wl > health relevance model  > stroke > 1",
    "skydeo > conditiongraph > disease propensity by type > stroke propensity",
    "peer39: health>conditions&diseases>cancer",
    "epsilon: healthcare > conditions > respiratory ailments > asthma",
    "crossix > crossix wl > diagnosis > leukemia > 3",
    "disease propensity by type > cancer: skin (adstra)",
    "peer39: custom category>pregnant_12-24 weeks",
    "peer39: custom category>pregnant_25 plus weeks",
    "2. pregnant women + ios + female + 21 thru 49 + hhi (2.12.18)_ pregnant mothers feb 2018",
    "33across > us m life events family planning",
    "crunchdmc_miscarriages (grapeshot)",
    "epsilon: healthcare > conditions > menopause",
    "doubleverify - dv: contextual>health & fitness>infertility",
    "clickagy > partners > engine group > healthcare/lifestyle > fertility treatment participant/information seekers",
    "eyeota - us plunge digital - interest - treatment - erectile dysfunction",
    "sharethis > people & society > disabled & special needs",
    "nielsen harris poll - employment status - unable to work due to a disability",
    "crunchdmc_blind_veterans (grapeshot)",
    "advertise_children_with_autism (grapeshot)",
    "mediaiq_adhd_medication_kws (grapeshot)",
    "crossix custom > health relevance model  > adhd recent adult diagnosis (shire) > 1",
    "prhlthmd_health_panic_anxiety (grapeshot)",
    "disease propensity by type > anxiety diagnosis (adstra)",
    "epsilon: healthcare > conditions > depression",
    "depression propensity - reach tier 3 (adstra)",
    "clickagy > health > addictions > gambling",
    "clickagy > health > addictions > drugs",
    "clickagy > health > addictions > alcohol",
    "nj_cannabis_af-american_device_cookie",
    "nj_cannabis_young_voters_v2_device_cookie",
    "prhlthmd_health_bipolar_disorder (grapeshot)",
    "prhlthmd_ps_major_depressive_disorder (grapeshot)",
    "brain and nervous system disorders ( behaviour )",
    "skydeo > interest > insomnia sufferers > likely",
    "twine > mobile apps > top mobile apps > grindr - gay chat",
    "lifestyle > political > lgbt activists - extreme confidence (dstillery)",
    "social profiles by type > lesbian/gay/bisexual/transgender (lgbt) supporters (adstra)",
    "delidatax sp - interest - gays and lesbianas (exelate)",
    "aud.gayfriendly lifestyle_estilo de vida (hd)_aud.gayfriendly lifestyle_estilo de vida (hd) appnexus",
    "tech targets - from whotoo - industry - memberships and organizations - labor unions (exelate)",
    "infogroup business and professional - industry - memberships and organizations - labor unions (exelate)",
    "epsilon: demographics > labor union members > highly likely",
    "epsilon: books & magazines > bible & devotional readers > highly likely",
    "33across audienceid - 33across interest segments - food - kosher",
    "catalina > product attributes >  ingredients  >  lifestyle diet  >  kosher lifestyle",
    "l2 voter data > individual demographics > parties description > communist",
    "deep root analytics > anti socialism",
    "very liberal/hard democrat (lotame)",
    "audience profiles > politics > female democratic supporter (cross pixel)",
    "lifestyle > political > right wing radicals - extreme confidence (dstillery)",
    "l2 voter data > lifestyle & issue data > haystaqdna > marijuana legalization > support",
    "lifestyle > activities > marijuana - extreme confidence (dstillery)",
    "marijuana user: active (adstra)",
    "skydeo > political pinpoints > voter profile > marriage equality supporters",
    "lifestyle > lifestage > visa & immigration (dstillery)",
    "lifestyle > lifestage > visa & immigration - extreme confidence (dstillery)",
    "truoptik>webbula>demographics>immigrant assimilation status > partially assimilated (bilingual - english primary)",
    "truoptik>webbula>demographics>immigrant assimilation status > partially assimilated (bilingual - native language primary)",
    "truoptik>webbula>demographics>immigrant assimilation status > unassimilated (native language)",
    "eyeota - au roy morgan - helix personas (2014) - 300 today's families - 305 successful immigrants",
    "eyeota - nz equifax - landscape - 305 successful immigrants",
    "infogroup > b2c > politics > issues > environment and energy > climate change > believers -- co-op sourced",
    "infogroup > b2c > politics > issues > environment and energy > climate change > non-believers -- co-op sourced",
]